name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: pnpmのセットアップ
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: 依存パッケージのインストール
        run: pnpm install

      - name: .envファイルの作成
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: ビルド
        run: pnpm build

      - name: デプロイ先の準備
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: mkdir -p ~/apps && mkdir -p ~/apps/ordinary-person-bot-production

      - name: デプロイ用ファイルの準備
        run: |
          mkdir -p deploy
          cp .tool-versions deploy/
          cp package-prod.json deploy/package.json
          cp dist/weekly.js deploy/

      - name: ファイル一括アップロード
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy/*"
          target: "~/apps/ordinary-person-bot-production"
          strip_components: 1
          overwrite: true
          timeout: 600s
          command_timeout: 600s
          use_insecure_cipher: true

      - name: サーバーでの依存関係のインストール
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/apps/ordinary-person-bot-production
            npm install -g pnpm
            pnpm install --prod
